[build]
  publish = "public"
  command = "yarn build"
  functions = "functions/dist"
[build.environment]
  YARN_VERSION = "1.10.1"
  YARN_FLAGS = "--no-ignore-optional"
  NODE_VERSION = "10.11.0"


# old redirect
[[redirects]]
  from = "http://snippet.terrierscript.com/*"
  to = "https://terrier.dev/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://snippets.terrierscript.com/*"
  to = "https://terrier.dev/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://snippets.terrier.dev/*"
  to = "https://terrier.dev/:splat"
  status = 301
  force = true

# old file redirect
[[redirects]]
  from = "/blog/20180*"
  to = "/blog/2018/20180:splat"
  status = 301
  force = true
[[redirects]]
  from = "/blog/20181*"
  to = "/blog/2018/20180:splat"
  status = 301
  force = true
[[redirects]]
  from = "/blog/20190*"
  to = "/blog/2019/20190:splat"
  status = 301
  force = true


# RSS 
[[redirects]]
  from = "/feed/qiita"
  to = "https://qiita.com/terrierscript/feed.atom"
  status = 200
  force = false
[[redirects]]
  from = "/feed/devto"
  to = "https://dev.to/feed/terrierscript"
  status = 200
  force = false
[[redirects]]
  from = "/feed/medium"
  to = "https://medium.com/feed/@terrierscript"
  status = 200
  force = false
[[redirects]]
  from = "/feed/snippet"
  to = "https://snippet.terrier.dev/rss.xml"
  status = 200
  force = false
[[redirects]]
  from = "/feed/scrapbox"
  to = "https://scrapbox.io/api/feed/terrierscript/"
  status = 200
  force = false
[[redirects]]
  from = "https://terrier.netlify.com/*"
  to = "https://terrierscript.com/:splat"
  status = 301
  force = true