[build]
  publish = "public"
  command = "yarn build"
  functions = "functions/dist"
[build.environment]
  YARN_VERSION = "1.10.1"
  YARN_FLAGS = "--no-ignore-optional"
  NODE_VERSION = "10.11.0"

[[redirects]]
  from = "/blog/20180*"
  to = "/blog/2018/20180:splat"
  status = 301
  force = true
[[redirects]]
  from = "/blog/20181*"
  to = "/blog/2018/20180:splat"
  status = 301
  force = true
[[redirects]]
  from = "/blog/20190*"
  to = "/blog/2019/20190:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://snippet.terrierscript.com/*"
  to = "https://snippet.terrier.dev/:splat"
  status = 301
  force = true
[[redirects]]
  from = "http://snippet.terrierscript.com/*"
  to = "https://snippet.terrier.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://snippets.terrierscript.com/*"
  to = "https://snippet.terrier.dev/:splat"
  status = 301
  force = true
[[redirects]]
  from = "http://snippets.terrierscript.com/*"
  to = "https://snippet.terrier.dev/:splat"
  status = 301
  force = true