[build]
  publish = "packages/core/public"
  command = "yarn build"
  functions = "lambda"
[build.environment]
  YARN_VERSION = "1.10.1"
  YARN_FLAGS = "--no-ignore-optional"
  NODE_VERSION = "10.11.0"
