[build]
  publish = "public"
  command = "yarn build"
  functions = "functions/dist"
[build.environment]
  YARN_VERSION = "1.10.1"
  YARN_FLAGS = "--no-ignore-optional"
  NODE_VERSION = "10.11.0"

[[redirects]]
  from = "/20180*"
  to = "/2018/20180:splat"
  status = 302
  force = false
[[redirects]]
  from = "/20190*"
  to = "/2019/20190:splat"
  status = 302
  force = false