version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout
      - run: apt-get install curl
      - run:
          name: Build
          command: curl -X POST -d {} $BUILD_URL
