name: Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - run: yarn install
    - run: yarn test
      env: # Or as an environment variable
        GITHUB_EMBED_TOKEN: ${{ secrets.GITHUB_EMBED_TOKEN }}
