name: Test

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: yarn install
    - run: yarn test
  tsc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: yarn install
    - run: yarn tsc
  jest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: yarn install
    - run: yarn jest
  lhci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: yarn install
    - run: yarn build
    - name: Audit URLs using Lighthouse
      uses: treosh/lighthouse-ci-action@v2
      with:
        staticDistDir: "./dist"
    - name: Save results
      uses: actions/upload-artifact@v1
      with:
        name: lighthouse-results
        path: '.lighthouseci'
